# Generated by Django 3.0 on 2019-12-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pleasantPup_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='health_info',
            new_name='health',
        ),
        migrations.RenameField(
            model_name='breed',
            old_name='image_link',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='image_link',
            new_name='image',
        ),
    ]
