# Generated by Django 3.0 on 2019-12-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleasantPup_app', '0002_auto_20191204_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='image',
        ),
        migrations.AlterField(
            model_name='breed',
            name='breed',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='breed',
            name='health',
            field=models.TextField(),
        ),
    ]
