# Generated by Django 3.0 on 2019-12-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleasantPup_app', '0003_auto_20191204_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='image',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='breed',
            name='breed',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='breed',
            name='health',
            field=models.CharField(max_length=2000),
        ),
    ]
