# Generated by Django 3.0 on 2019-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pleasantPup_app', '0004_auto_20191204_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='image',
            new_name='care',
        ),
        migrations.AddField(
            model_name='breed',
            name='history_background',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='breed',
            name='image_link',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='breed',
            name='personality_temperament',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='breed',
            name='physical_characteristics',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='breed',
            name='health',
            field=models.TextField(default=0),
        ),
    ]
