# Generated by Django 2.2.7 on 2019-12-04 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pleasantPup_app', '0005_auto_20191204_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='image',
        ),
        migrations.AlterField(
            model_name='breed',
            name='image_link',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(default='No content provided')),
                ('image_link', models.TextField(default='No image provided')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DogProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField(default=0)),
                ('image', models.TextField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DogProfiles', to='pleasantPup_app.Dog')),
            ],
        ),
    ]
