# Generated by Django 2.2.7 on 2019-12-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pleasantPup_app', '0007_auto_20191204_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogprofile',
            old_name='image',
            new_name='image_link',
        ),
    ]
